In [3]:
%matplotlib inline

import numpy as np
import matplotlib.pyplot as plt

# 複習

In [6]:
# Define a new currency
def gold2twd(gold):
    
    twd = gold*100
    print(f'{gold}金幣合{twd}台幣')

In [7]:
gold2twd(10)

10金幣合1000台幣


In [8]:
def gold2twd(gold, c = 100):
    
    twd = gold * c
    print(f'{gold}金幣合{twd}台幣')

In [9]:
gold2twd(10)

10金幣合1000台幣


In [11]:
gold2twd(10, c = 10000) #可以隨時改變參數

10金幣合100000台幣


# List 與 Array 的不同

In [12]:
l = list(range(10))

In [13]:
l

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [33]:
k = np.arange(1,10,1)

In [34]:
k

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
l * 2

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [36]:
k * 2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [37]:
k.mean()

5.0

In [38]:
np.mean(k)

5.0

In [39]:
np.median(k)

5.0

In [40]:
k.std()

2.581988897471611

In [41]:
max(k)

9

In [42]:
k.min()

1

In [43]:
k.cumsum() #cumulated sum 累加

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45], dtype=int32)

In [44]:
k.prod()

362880

In [45]:
k.cumprod()

array([     1,      2,      6,     24,    120,    720,   5040,  40320,
       362880], dtype=int32)

In [47]:
n = k.reshape(3,3) # Only array can be reshaped

In [48]:
n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [49]:
n.mean()

5.0

In [51]:
n.mean(axis=0) #行

array([4., 5., 6.])

In [52]:
n.mean(axis=1)

array([2., 5., 8.])

In [54]:
np.random.seed(1) #取亂數模式

In [55]:
np.random.randint(10)

5

In [57]:
num = 0
while num<5:
    np.random.seed(1) 
    print(np.random.randint(10))
    num += 1

5
5
5
5
5


In [59]:
num = 0
np.random.seed(1) #random.seed() 只會生效一次
while num<5:
     
    print(np.random.randint(10))
    num += 1

5
8
9
5
0


In [62]:
np.random.rand(5,5) #以0為mean，1為std取值(常態分布)

array([[0.34556073, 0.39676747, 0.53881673, 0.41919451, 0.6852195 ],
       [0.20445225, 0.87811744, 0.02738759, 0.67046751, 0.4173048 ],
       [0.55868983, 0.14038694, 0.19810149, 0.80074457, 0.96826158],
       [0.31342418, 0.69232262, 0.87638915, 0.89460666, 0.08504421],
       [0.03905478, 0.16983042, 0.8781425 , 0.09834683, 0.42110763]])

In [63]:
s = ['a','b','c','d','e']

In [64]:
np.random.choice(s)

'b'

In [65]:
np.random.choice(s,3)

array(['b', 'd', 'e'], dtype='<U1')

In [68]:
np.random.choice(s,5)

array(['a', 'e', 'b', 'c', 'c'], dtype='<U1')

In [69]:
np.random.choice(s,5, replace = False) #不重複取樣

array(['d', 'e', 'c', 'a', 'b'], dtype='<U1')

In [71]:
np.random.choice(s, size = (3,3))

array([['d', 'e', 'd'],
       ['b', 'd', 'a'],
       ['a', 'c', 'c']], dtype='<U1')

In [72]:
P = [0.8, 0.2, 0, 0, 0] # Set probability

In [74]:
np.random.choice(s,10,p = P)

array(['a', 'a', 'a', 'a', 'b', 'a', 'b', 'a', 'a', 'b'], dtype='<U1')